name: Autopilot Update ðŸš€

on:
  schedule:
    # Esegue ogni giorno alle 09:00 italiane
    - cron: '0 8 * * *'
  workflow_dispatch: # Permette di avviarlo a mano col bottone

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # DÃ  il permesso di salvare i prezzi aggiornati
    
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa librerie
        run: pip install pandas yfinance

      - name: Esegui Analisi e Aggiorna Sito
        run: python main.py

      - name: Salva modifiche nel Cloud
        run: |
          git config --global user.name "Insider Bot"
          git config --global user.email "bot@marketinsider.pro"
          git add .
          git commit -m "ðŸ¤– Aggiornamento Automatico" || echo "Nessuna modifica"
          git push